version: '2'

services:
 web-python:
   image: laszlocph/composetest
   ports:
    - "${PORT}:5000"
   depends_on:
    - redis
 boot:
   image: laszlocph/spring-boot-dummy #https://api.github.com/repos/laszlocph/spring-boot-dummy/branches
 redis:
   image: redis
